/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.learnkafka.avro.schema;
@SuppressWarnings("all")
/** Type of the library event */
@org.apache.avro.specific.AvroGenerated
public enum LibraryEventType {
  NEW, UPDATE, DELETE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"LibraryEventType\",\"namespace\":\"com.learnkafka.avro.schema\",\"doc\":\"Type of the library event\",\"symbols\":[\"NEW\",\"UPDATE\",\"DELETE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
