/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.learnkafka.avro.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class LibraryEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8731851212759018502L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LibraryEvent\",\"namespace\":\"com.learnkafka.avro.schema\",\"fields\":[{\"name\":\"libraryEventId\",\"type\":\"string\"},{\"name\":\"libraryEventType\",\"type\":{\"type\":\"enum\",\"name\":\"LibraryEventType\",\"doc\":\"Type of the library event\",\"symbols\":[\"NEW\",\"UPDATE\",\"DELETE\"]},\"doc\":\"Indicates the operation: NEW, UPDATE or DELETE\",\"default\":\"NEW\"},{\"name\":\"book\",\"type\":{\"type\":\"record\",\"name\":\"Book\",\"fields\":[{\"name\":\"bookId\",\"type\":\"int\"},{\"name\":\"bookName\",\"type\":\"string\"},{\"name\":\"bookAuthor\",\"type\":\"string\"}]}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LibraryEvent> ENCODER =
      new BinaryMessageEncoder<LibraryEvent>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LibraryEvent> DECODER =
      new BinaryMessageDecoder<LibraryEvent>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<LibraryEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<LibraryEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LibraryEvent>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this LibraryEvent to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a LibraryEvent from a ByteBuffer. */
  public static LibraryEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.CharSequence libraryEventId;
  /** Indicates the operation: NEW, UPDATE or DELETE */
  @Deprecated public com.learnkafka.avro.schema.LibraryEventType libraryEventType;
  @Deprecated public com.learnkafka.avro.schema.Book book;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LibraryEvent() {}

  /**
   * All-args constructor.
   * @param libraryEventId The new value for libraryEventId
   * @param libraryEventType Indicates the operation: NEW, UPDATE or DELETE
   * @param book The new value for book
   */
  public LibraryEvent(java.lang.CharSequence libraryEventId, com.learnkafka.avro.schema.LibraryEventType libraryEventType, com.learnkafka.avro.schema.Book book) {
    this.libraryEventId = libraryEventId;
    this.libraryEventType = libraryEventType;
    this.book = book;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return libraryEventId;
    case 1: return libraryEventType;
    case 2: return book;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: libraryEventId = (java.lang.CharSequence)value$; break;
    case 1: libraryEventType = (com.learnkafka.avro.schema.LibraryEventType)value$; break;
    case 2: book = (com.learnkafka.avro.schema.Book)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'libraryEventId' field.
   * @return The value of the 'libraryEventId' field.
   */
  public java.lang.CharSequence getLibraryEventId() {
    return libraryEventId;
  }

  /**
   * Sets the value of the 'libraryEventId' field.
   * @param value the value to set.
   */
  public void setLibraryEventId(java.lang.CharSequence value) {
    this.libraryEventId = value;
  }

  /**
   * Gets the value of the 'libraryEventType' field.
   * @return Indicates the operation: NEW, UPDATE or DELETE
   */
  public com.learnkafka.avro.schema.LibraryEventType getLibraryEventType() {
    return libraryEventType;
  }

  /**
   * Sets the value of the 'libraryEventType' field.
   * Indicates the operation: NEW, UPDATE or DELETE
   * @param value the value to set.
   */
  public void setLibraryEventType(com.learnkafka.avro.schema.LibraryEventType value) {
    this.libraryEventType = value;
  }

  /**
   * Gets the value of the 'book' field.
   * @return The value of the 'book' field.
   */
  public com.learnkafka.avro.schema.Book getBook() {
    return book;
  }

  /**
   * Sets the value of the 'book' field.
   * @param value the value to set.
   */
  public void setBook(com.learnkafka.avro.schema.Book value) {
    this.book = value;
  }

  /**
   * Creates a new LibraryEvent RecordBuilder.
   * @return A new LibraryEvent RecordBuilder
   */
  public static com.learnkafka.avro.schema.LibraryEvent.Builder newBuilder() {
    return new com.learnkafka.avro.schema.LibraryEvent.Builder();
  }

  /**
   * Creates a new LibraryEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LibraryEvent RecordBuilder
   */
  public static com.learnkafka.avro.schema.LibraryEvent.Builder newBuilder(com.learnkafka.avro.schema.LibraryEvent.Builder other) {
    return new com.learnkafka.avro.schema.LibraryEvent.Builder(other);
  }

  /**
   * Creates a new LibraryEvent RecordBuilder by copying an existing LibraryEvent instance.
   * @param other The existing instance to copy.
   * @return A new LibraryEvent RecordBuilder
   */
  public static com.learnkafka.avro.schema.LibraryEvent.Builder newBuilder(com.learnkafka.avro.schema.LibraryEvent other) {
    return new com.learnkafka.avro.schema.LibraryEvent.Builder(other);
  }

  /**
   * RecordBuilder for LibraryEvent instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LibraryEvent>
    implements org.apache.avro.data.RecordBuilder<LibraryEvent> {

    private java.lang.CharSequence libraryEventId;
    /** Indicates the operation: NEW, UPDATE or DELETE */
    private com.learnkafka.avro.schema.LibraryEventType libraryEventType;
    private com.learnkafka.avro.schema.Book book;
    private com.learnkafka.avro.schema.Book.Builder bookBuilder;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.learnkafka.avro.schema.LibraryEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.libraryEventId)) {
        this.libraryEventId = data().deepCopy(fields()[0].schema(), other.libraryEventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.libraryEventType)) {
        this.libraryEventType = data().deepCopy(fields()[1].schema(), other.libraryEventType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.book)) {
        this.book = data().deepCopy(fields()[2].schema(), other.book);
        fieldSetFlags()[2] = true;
      }
      if (other.hasBookBuilder()) {
        this.bookBuilder = com.learnkafka.avro.schema.Book.newBuilder(other.getBookBuilder());
      }
    }

    /**
     * Creates a Builder by copying an existing LibraryEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.learnkafka.avro.schema.LibraryEvent other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.libraryEventId)) {
        this.libraryEventId = data().deepCopy(fields()[0].schema(), other.libraryEventId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.libraryEventType)) {
        this.libraryEventType = data().deepCopy(fields()[1].schema(), other.libraryEventType);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.book)) {
        this.book = data().deepCopy(fields()[2].schema(), other.book);
        fieldSetFlags()[2] = true;
      }
      this.bookBuilder = null;
    }

    /**
      * Gets the value of the 'libraryEventId' field.
      * @return The value.
      */
    public java.lang.CharSequence getLibraryEventId() {
      return libraryEventId;
    }

    /**
      * Sets the value of the 'libraryEventId' field.
      * @param value The value of 'libraryEventId'.
      * @return This builder.
      */
    public com.learnkafka.avro.schema.LibraryEvent.Builder setLibraryEventId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.libraryEventId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'libraryEventId' field has been set.
      * @return True if the 'libraryEventId' field has been set, false otherwise.
      */
    public boolean hasLibraryEventId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'libraryEventId' field.
      * @return This builder.
      */
    public com.learnkafka.avro.schema.LibraryEvent.Builder clearLibraryEventId() {
      libraryEventId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'libraryEventType' field.
      * Indicates the operation: NEW, UPDATE or DELETE
      * @return The value.
      */
    public com.learnkafka.avro.schema.LibraryEventType getLibraryEventType() {
      return libraryEventType;
    }

    /**
      * Sets the value of the 'libraryEventType' field.
      * Indicates the operation: NEW, UPDATE or DELETE
      * @param value The value of 'libraryEventType'.
      * @return This builder.
      */
    public com.learnkafka.avro.schema.LibraryEvent.Builder setLibraryEventType(com.learnkafka.avro.schema.LibraryEventType value) {
      validate(fields()[1], value);
      this.libraryEventType = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'libraryEventType' field has been set.
      * Indicates the operation: NEW, UPDATE or DELETE
      * @return True if the 'libraryEventType' field has been set, false otherwise.
      */
    public boolean hasLibraryEventType() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'libraryEventType' field.
      * Indicates the operation: NEW, UPDATE or DELETE
      * @return This builder.
      */
    public com.learnkafka.avro.schema.LibraryEvent.Builder clearLibraryEventType() {
      libraryEventType = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'book' field.
      * @return The value.
      */
    public com.learnkafka.avro.schema.Book getBook() {
      return book;
    }

    /**
      * Sets the value of the 'book' field.
      * @param value The value of 'book'.
      * @return This builder.
      */
    public com.learnkafka.avro.schema.LibraryEvent.Builder setBook(com.learnkafka.avro.schema.Book value) {
      validate(fields()[2], value);
      this.bookBuilder = null;
      this.book = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'book' field has been set.
      * @return True if the 'book' field has been set, false otherwise.
      */
    public boolean hasBook() {
      return fieldSetFlags()[2];
    }

    /**
     * Gets the Builder instance for the 'book' field and creates one if it doesn't exist yet.
     * @return This builder.
     */
    public com.learnkafka.avro.schema.Book.Builder getBookBuilder() {
      if (bookBuilder == null) {
        if (hasBook()) {
          setBookBuilder(com.learnkafka.avro.schema.Book.newBuilder(book));
        } else {
          setBookBuilder(com.learnkafka.avro.schema.Book.newBuilder());
        }
      }
      return bookBuilder;
    }

    /**
     * Sets the Builder instance for the 'book' field
     * @param value The builder instance that must be set.
     * @return This builder.
     */
    public com.learnkafka.avro.schema.LibraryEvent.Builder setBookBuilder(com.learnkafka.avro.schema.Book.Builder value) {
      clearBook();
      bookBuilder = value;
      return this;
    }

    /**
     * Checks whether the 'book' field has an active Builder instance
     * @return True if the 'book' field has an active Builder instance
     */
    public boolean hasBookBuilder() {
      return bookBuilder != null;
    }

    /**
      * Clears the value of the 'book' field.
      * @return This builder.
      */
    public com.learnkafka.avro.schema.LibraryEvent.Builder clearBook() {
      book = null;
      bookBuilder = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LibraryEvent build() {
      try {
        LibraryEvent record = new LibraryEvent();
        record.libraryEventId = fieldSetFlags()[0] ? this.libraryEventId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.libraryEventType = fieldSetFlags()[1] ? this.libraryEventType : (com.learnkafka.avro.schema.LibraryEventType) defaultValue(fields()[1]);
        if (bookBuilder != null) {
          record.book = this.bookBuilder.build();
        } else {
          record.book = fieldSetFlags()[2] ? this.book : (com.learnkafka.avro.schema.Book) defaultValue(fields()[2]);
        }
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LibraryEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<LibraryEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LibraryEvent>
    READER$ = (org.apache.avro.io.DatumReader<LibraryEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
