/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.learnkafka.avro.schema;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Book extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7456762941925932347L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Book\",\"namespace\":\"com.learnkafka.avro.schema\",\"fields\":[{\"name\":\"bookId\",\"type\":\"int\"},{\"name\":\"bookName\",\"type\":\"string\"},{\"name\":\"bookAuthor\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Book> ENCODER =
      new BinaryMessageEncoder<Book>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Book> DECODER =
      new BinaryMessageDecoder<Book>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<Book> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<Book> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Book>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this Book to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a Book from a ByteBuffer. */
  public static Book fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public int bookId;
  @Deprecated public java.lang.CharSequence bookName;
  @Deprecated public java.lang.CharSequence bookAuthor;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Book() {}

  /**
   * All-args constructor.
   * @param bookId The new value for bookId
   * @param bookName The new value for bookName
   * @param bookAuthor The new value for bookAuthor
   */
  public Book(java.lang.Integer bookId, java.lang.CharSequence bookName, java.lang.CharSequence bookAuthor) {
    this.bookId = bookId;
    this.bookName = bookName;
    this.bookAuthor = bookAuthor;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bookId;
    case 1: return bookName;
    case 2: return bookAuthor;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bookId = (java.lang.Integer)value$; break;
    case 1: bookName = (java.lang.CharSequence)value$; break;
    case 2: bookAuthor = (java.lang.CharSequence)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'bookId' field.
   * @return The value of the 'bookId' field.
   */
  public java.lang.Integer getBookId() {
    return bookId;
  }

  /**
   * Sets the value of the 'bookId' field.
   * @param value the value to set.
   */
  public void setBookId(java.lang.Integer value) {
    this.bookId = value;
  }

  /**
   * Gets the value of the 'bookName' field.
   * @return The value of the 'bookName' field.
   */
  public java.lang.CharSequence getBookName() {
    return bookName;
  }

  /**
   * Sets the value of the 'bookName' field.
   * @param value the value to set.
   */
  public void setBookName(java.lang.CharSequence value) {
    this.bookName = value;
  }

  /**
   * Gets the value of the 'bookAuthor' field.
   * @return The value of the 'bookAuthor' field.
   */
  public java.lang.CharSequence getBookAuthor() {
    return bookAuthor;
  }

  /**
   * Sets the value of the 'bookAuthor' field.
   * @param value the value to set.
   */
  public void setBookAuthor(java.lang.CharSequence value) {
    this.bookAuthor = value;
  }

  /**
   * Creates a new Book RecordBuilder.
   * @return A new Book RecordBuilder
   */
  public static com.learnkafka.avro.schema.Book.Builder newBuilder() {
    return new com.learnkafka.avro.schema.Book.Builder();
  }

  /**
   * Creates a new Book RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Book RecordBuilder
   */
  public static com.learnkafka.avro.schema.Book.Builder newBuilder(com.learnkafka.avro.schema.Book.Builder other) {
    return new com.learnkafka.avro.schema.Book.Builder(other);
  }

  /**
   * Creates a new Book RecordBuilder by copying an existing Book instance.
   * @param other The existing instance to copy.
   * @return A new Book RecordBuilder
   */
  public static com.learnkafka.avro.schema.Book.Builder newBuilder(com.learnkafka.avro.schema.Book other) {
    return new com.learnkafka.avro.schema.Book.Builder(other);
  }

  /**
   * RecordBuilder for Book instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Book>
    implements org.apache.avro.data.RecordBuilder<Book> {

    private int bookId;
    private java.lang.CharSequence bookName;
    private java.lang.CharSequence bookAuthor;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.learnkafka.avro.schema.Book.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bookName)) {
        this.bookName = data().deepCopy(fields()[1].schema(), other.bookName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bookAuthor)) {
        this.bookAuthor = data().deepCopy(fields()[2].schema(), other.bookAuthor);
        fieldSetFlags()[2] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing Book instance
     * @param other The existing instance to copy.
     */
    private Builder(com.learnkafka.avro.schema.Book other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.bookId)) {
        this.bookId = data().deepCopy(fields()[0].schema(), other.bookId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bookName)) {
        this.bookName = data().deepCopy(fields()[1].schema(), other.bookName);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bookAuthor)) {
        this.bookAuthor = data().deepCopy(fields()[2].schema(), other.bookAuthor);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'bookId' field.
      * @return The value.
      */
    public java.lang.Integer getBookId() {
      return bookId;
    }

    /**
      * Sets the value of the 'bookId' field.
      * @param value The value of 'bookId'.
      * @return This builder.
      */
    public com.learnkafka.avro.schema.Book.Builder setBookId(int value) {
      validate(fields()[0], value);
      this.bookId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'bookId' field has been set.
      * @return True if the 'bookId' field has been set, false otherwise.
      */
    public boolean hasBookId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'bookId' field.
      * @return This builder.
      */
    public com.learnkafka.avro.schema.Book.Builder clearBookId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'bookName' field.
      * @return The value.
      */
    public java.lang.CharSequence getBookName() {
      return bookName;
    }

    /**
      * Sets the value of the 'bookName' field.
      * @param value The value of 'bookName'.
      * @return This builder.
      */
    public com.learnkafka.avro.schema.Book.Builder setBookName(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.bookName = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'bookName' field has been set.
      * @return True if the 'bookName' field has been set, false otherwise.
      */
    public boolean hasBookName() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'bookName' field.
      * @return This builder.
      */
    public com.learnkafka.avro.schema.Book.Builder clearBookName() {
      bookName = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'bookAuthor' field.
      * @return The value.
      */
    public java.lang.CharSequence getBookAuthor() {
      return bookAuthor;
    }

    /**
      * Sets the value of the 'bookAuthor' field.
      * @param value The value of 'bookAuthor'.
      * @return This builder.
      */
    public com.learnkafka.avro.schema.Book.Builder setBookAuthor(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.bookAuthor = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'bookAuthor' field has been set.
      * @return True if the 'bookAuthor' field has been set, false otherwise.
      */
    public boolean hasBookAuthor() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'bookAuthor' field.
      * @return This builder.
      */
    public com.learnkafka.avro.schema.Book.Builder clearBookAuthor() {
      bookAuthor = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Book build() {
      try {
        Book record = new Book();
        record.bookId = fieldSetFlags()[0] ? this.bookId : (java.lang.Integer) defaultValue(fields()[0]);
        record.bookName = fieldSetFlags()[1] ? this.bookName : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.bookAuthor = fieldSetFlags()[2] ? this.bookAuthor : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Book>
    WRITER$ = (org.apache.avro.io.DatumWriter<Book>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Book>
    READER$ = (org.apache.avro.io.DatumReader<Book>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
